[platformio]
src_dir = firmware/main

[env:opencm904]
platform = ststm32
board = genericSTM32F103CB
framework = arduino
monitor_speed = 115200

lib_deps = 
    robotis-git/Dynamixel2Arduino


build_flags = 
    -I firmware/headers
    -I configs
    -I cores/opencm904
    -I variants/opencm904
    -D STM32F1
    -D STM32F103xB
    -D OPENCM904
    -D VARIANT_OPENCM904


build_src_filter = 
    +<*>
    -<.git/>
    -<.svn/>

extra_scripts = 
   